# Project Metadata
sonar.organization=huypham67
sonar.projectKey=huypham67_user-service
sonar.projectName=user-service
sonar.projectVersion=1.0

# Scope & Encoding
sonar.sources=.
sonar.tests=.
sonar.sourceEncoding=UTF-8
