// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	health "github.com/huypham67/user-service/internal/dto/health"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetStatus provides a mock function with given fields: ctx
func (_m *Service) GetStatus(ctx context.Context) health.HealthCheckResponse {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 health.HealthCheckResponse
	if rf, ok := ret.Get(0).(func(context.Context) health.HealthCheckResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(health.HealthCheckResponse)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
